### ISSUE TITLE
How to install the package from source? Getting errors with `setup.py`

### ISSUE THREAD

**Issue by doronbehar** [MeirKriheli/python-bidi#9]
As the title suggests, I'm getting various errors when trying to install the package from source. Here is the Traceback:
```
running install
running build
running build_py
running install_lib
creating /var/cache/aursync/python-pybidi/pkg/usr
creating /var/cache/aursync/python-pybidi/pkg/usr/lib
creating /var/cache/aursync/python-pybidi/pkg/usr/lib/python3.6
creating /var/cache/aursync/python-pybidi/pkg/usr/lib/python3.6/site-packages
creating /var/cache/aursync/python-pybidi/pkg/usr/lib/python3.6/site-packages/bidi
copying build/lib/bidi/__init__.py -> /var/cache/aursync/python-pybidi/pkg/usr/lib/python3.6/site-packages/bidi
copying build/lib/bidi/mirror.py -> /var/cache/aursync/python-pybidi/pkg/usr/lib/python3.6/site-packages/bidi
copying build/lib/bidi/algorithm.py -> /var/cache/aursync/python-pybidi/pkg/usr/lib/python3.6/site-packages/bidi
byte-compiling /var/cache/aursync/python-pybidi/pkg/usr/lib/python3.6/site-packages/bidi/__init__.py to __init__.cpython-36.pyc
byte-compiling /var/cache/aursync/python-pybidi/pkg/usr/lib/python3.6/site-packages/bidi/mirror.py to mirror.cpython-36.pyc
byte-compiling /var/cache/aursync/python-pybidi/pkg/usr/lib/python3.6/site-packages/bidi/algorithm.py to algorithm.cpython-36.pyc
writing byte-compilation script '/tmp/tmpwxe2eg7z.py'
/usr/bin/python /tmp/tmpwxe2eg7z.py
removing /tmp/tmpwxe2eg7z.py
running install_egg_info
running egg_info
writing python_bidi.egg-info/PKG-INFO
writing dependency_links to python_bidi.egg-info/dependency_links.txt
writing entry points to python_bidi.egg-info/entry_points.txt
writing requirements to python_bidi.egg-info/requires.txt
writing top-level names to python_bidi.egg-info/top_level.txt
fatal: Not a valid object name
Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 2295, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.6/tarfile.py", line 1091, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.6/tarfile.py", line 1027, in frombuf
    raise EmptyHeaderError("empty header")
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    tests_require=test_requirements,
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib/python3.6/distutils/command/install.py", line 557, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/install_egg_info.py", line 34, in run
    self.run_command('egg_info')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 278, in run
    self.find_sources()
  File "/usr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
    mm.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 524, in run
    self.add_defaults()
  File "/usr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 563, in add_defaults
    rcfiles = list(walk_revctrl())
  File "/usr/lib/python3.6/site-packages/setuptools/command/sdist.py", line 20, in walk_revctrl
    for item in ep.load()(dirname):
  File "/usr/lib/python3.6/site-packages/setuptools_scm/integration.py", line 32, in find_files
    res = command(path)
  File "/usr/lib/python3.6/site-packages/setuptools_scm/file_finder_git.py", line 44, in git_find_files
    git_files, git_dirs = _git_ls_files_and_dirs(toplevel)
  File "/usr/lib/python3.6/site-packages/setuptools_scm/file_finder_git.py", line 28, in _git_ls_files_and_dirs
    tf = tarfile.open(fileobj=proc.stdout, mode='r|*')
  File "/usr/lib/python3.6/tarfile.py", line 1599, in open
    t = cls(name, filemode, stream, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1480, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.6/tarfile.py", line 2310, in next
    raise ReadError("empty file")
tarfile.ReadError: empty file
```
I'd like to install the package from source because I'm trying to package this to the Arch Linux user repositories.

Couldn't find anything when googling the exceptions given here. I'd be happy to get some help with this. I think it's a problem with the `setup.py` but I'm not sure.

Thanks

**Comment by MeirKriheli** [comment]
I've ran `python setup.py install` in a virtualenv (on Arch), worked without a problem.

**Comment by doronbehar** [comment]
I don't use Arch anymore and my distro now provides this package and I don't even need it so feel free to close it as probably things have changed now...

**Comment by MeirKriheli** [comment]
Thanks
